export const AUTH_USER_REQUEST = 'auth/AUTH_USER_REQUEST'
export const AUTH_USER_SUCCESS = 'auth/AUTH_USER_SUCCESS'
export const AUTH_USER_FAILURE = 'auth/AUTH_USER_FAILURE'

export const REGISTER_USER_REQUEST = 'auth/REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'auth/REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'auth/REGISTER_USER_FAILURE'
