export const GET_ALL_CATEGORY_REQUEST = 'project/GET_ALL_CATEGORY_REQUEST'
export const GET_ALL_CATEGORY_SUCCESS = 'project/GET_ALL_CATEGORY_SUCCESS'
export const GET_ALL_CATEGORY_FAILURE = 'project/GET_ALL_CATEGORY_FAILURE'
