export const GET_ALL_LIST_REQUEST = 'link/GET_ALL_LIST_REQUEST'
export const GET_ALL_LIST_SUCCESS = 'link/GET_ALL_LIST_SUCCESS'
export const GET_ALL_LIST_FAILURE = 'link/GET_ALL_LIST_FAILURE'

export const CREATE_LINK_REQUEST = 'link/CREATE_LINK_REQUEST'
export const CREATE_LINK_SUCCESS = 'link/CREATE_LINK_SUCCESS'
export const CREATE_LINK_FAILURE = 'link/CREATE_LINK_FAILURE'

export const UPDATE_LINK_REQUEST = 'link/UPDATE_LINK_REQUEST'
export const UPDATE_LINK_SUCCESS = 'link/UPDATE_LINK_SUCCESS'
export const UPDATE_LINK_FAILURE = 'link/UPDATE_LINK_FAILURE'
